sudo: false
language: nix
script: nix-build --argstr date "$(date --date=@$(git log -1 --pretty=%ct) +%F)"

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    repo: fsi-tue/satzung
